- type: job
  id: Brigguard
  name: job-name-Brigguard
  description: job-description-brigguard
  playTimeTracker: JobBrigguard
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hrs
  startingGear: BrigGuardGear
  icon: "JobIconBrigGuard"
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigGuardGear
  equipment:
    ears: ClothingHeadsetSecurity
  storage:
    back:
      - Flash
