- type: job
  id: Dutyofficer
  name: job-name-Dutyofficer
  description: job-description-Dutyofficer
  playTimeTracker: JobDutyofficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 # 10 hrs
  startingGear: DutyofficerGear
  icon: "JobIconDutyofficer"
  supervisors: job-supervisors-warden
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DutyofficerGear
  equipment:
    ears: ClothingHeadsetSecurity
  storage:
    back:
      - Flash
